---
exclude: ^codegen_lab/alembic/.*
# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit
ci:
  # Message used when pre-commit auto-fixes issues
  autofix_commit_msg: "style: pre-commit fixes"
  # Whether to auto-fix PRs
  autofix_prs: true
  # Branch to update when auto-updating hooks
  autoupdate_branch: ""
  # Message used when auto-updating hooks
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  # How often to auto-update hooks
  autoupdate_schedule: weekly
  # List of hooks to skip in CI
  skip: []
  # Whether to process git submodules
  submodules: false
default_install_hook_types:
  # Runs before commit is finalized, checks staged changes
  - pre-commit
  # Validates commit messages
  - commit-msg
  # Runs before push operation
  - pre-push
  # Runs after checkout operation
  - post-checkout
  # Runs after merge operation
  - post-merge
default_stages:
  # Run during git commit
  - pre-commit
  # Run during git push
  - pre-push
  # Run during git merge
  - pre-merge-commit
  # Run during git rebase
  - pre-rebase
repos:
  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.8
    hooks:
      - id: alphabetize-codeowners
      - id: fix-smartquotes
      - id: fix-ligatures

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, json]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Simply check whether files parse as valid python.
      - id: check-ast
      - id: check-json
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-log-warn
      - id: text-unicode-replacement-char

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
    hooks:
      - id: check-github-workflows
      - id: check-readthedocs

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.7.0
    hooks:
      - id: zizmor

  # GitHub Actions linting
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        name: Lint GitHub Actions workflow files
        description: Runs actionlint to lint GitHub Actions workflow files
        language: system
        types: ["yaml", "yml"]
        files: ^\.github/workflows/
        entry: actionlint
        minimum_pre_commit_version: 3.0.0
